Attornado/protein-reconstruction

preprocessing/constants.py, preprocessing/preprocessing_script.py
Refactored some constants and fixed some minor bugs.
=> Refactored some constants and fixed some minor bugs

preprocessing/dataset.py, preprocessing/preprocessing_script.py
Removed some old comments and updated some others.
=> Removed some old comments and updated some others.

preprocessing/constants.py, preprocessing/preprocessing_script.py, preprocessing/utils.py
Started creation of the main preprocessing script, defining various utility functions and constants.
=> Started creation of the main preprocessing script, defining various utility functions and constants

preprocessing/constants.py, preprocessing/dataset.py, preprocessing/preprocessing_script.py, preprocessing/utils.py
plus small refactoring in other modules.
=> modified function in dataset module

preprocessing/constants.py, preprocessing/dataset.py, preprocessing/preprocessing_script.py, preprocessing/utils.py
Fixed some bugs and refactored some functions to make the pre-training dataset creation actually working.
=> Fixed some bugs and refactored some functions to make the pre-training dataset creation actually working

preprocessing/preprocessing_script.py
=> Removed old TODO

evaluation/constants.py, training/constants.py
Created the core files to define the project structure.
=> Created the core files to define the project structure

models/layers.py
Defined two base layers for the future models.
=> Defined two base layers for the future models

models/layers.py, models/pretraining/gae.py
Create encoder classes for graph autoencoder.
=> Create encoder classes for graph autoencoder

models/pretraining/encoders.py, preprocessing/dataset.py, preprocessing/utils.py
Added support to additional node features like amino-acid one-hot encoding and meiler residue embedding, refactoring related functionalities.
=> Added support to additional node features like amino-acid one-hot encoding and meiler residue embedding, refactoring related functionalities

models/pretraining/gae.py, preprocessing/dataset.py
Added transformation function to better format the node features.
=> Added transformation function to better format the node features

preprocessing/dataset.py
=> Small documentation fixes

models/pretraining/graph_infomax.py
Small fix on random sam.pling in custom corruption function
=> Small fix on random sampling in custom corruption function

models/layers.py, models/pretraining/encoders.py, models/pretraining/gae.py, models/pretraining/vgae.py, preprocessing/preprocessing_script.py
Added several new layer types, refactored all the other layers and created training loops for GAE and VGAE.
=> Added several new layer types, refactored all the other layers and created training loops for GAE and VGAE

preprocessing/preprocessing_script.py, training/pytorchtools.py
Added EarlyStopping class from Bjarten/early-stopping-pytorch repository, available at https://github.com/Bjarten/early-stopping-pytorch
=> Added EarlyStopping class from Bjarten/early-stopping-pytorch repository

preprocessing/preprocessing_script.py
Minor fixes on preprocessing script.
=> Minor fixes on preprocessing script

models/pretraining/gae.py, models/pretraining/vgae.py, training/pretraining/graph_infomax_train_script.py, training/training_tools.py
Added early stopping to training .
=> Added early stopping to training 

models/pretraining/graph_infomax.py, training/pretraining/graph_infomax_train_script.py
Signed-off-by: Attornado <73835871+Attornado@users.noreply.github.com>
=> Started infomax training func

models/pretraining/gae.py
=> Small checkstyle fix

models/pretraining/graph_infomax.py
Fixes small bug in infomax trainer.
=> Fixes small bug in infomax trainer

models/layers.py, models/pretraining/encoders.py, models/pretraining/gae.py, models/pretraining/graph_infomax.py, models/pretraining/vgae.py
Started off model serialization methods. Testing still required.
=> Started off model serialization methods. Testing still required.

models/pretraining/encoders.py, models/pretraining/graph_infomax.py
=> Added TODO

models/layers.py, models/pretraining/gae.py, models/pretraining/graph_infomax.py, models/pretraining/vgae.py
Added documentation, implemented serialization for DGI model and fixed some serialization issues with VGAE.
=> Added documentation, implemented serialization for DGI model and fixed some serialization issues with VGAE

models/layers.py, models/pretraining/encoders.py
=> Fixed small bug in GCN2

training/training_tools.py
=> Small fixes

models/pretraining/graph_infomax.py, training/pretraining/graph_infomax_train_script.py
Fixed some bugs with the RandomSamplerCorruption class.
=> Fixed some bugs with the RandomSamplerCorruption class

models/pretraining/graph_infomax.py, tests/dgi_test.py, training/pretraining/graph_infomax_train_script.py
=> Fixed bugs in DGI metrics

models/pretraining/graph_infomax.py, training/pretraining/graph_infomax_train_script.py
Fixed bugs in DGI readout function.
=> Fixed bugs in DGI readout function

models/pretraining/graph_infomax.py, training/pretraining/graph_infomax_train_script.py
Fixed various bugs in the DGI metrics calculation.
=> Fixed various bugs in the DGI metrics calculation

models/pretraining/graph_infomax.py
Added an abstract class representing a corruption function and a new random permutation corruption function.
=> Added an abstract class representing a corruption function and a new random permutation corruption function

models/classification/classifiers.py, training/pretraining/graph_infomax_train_script.py
=> Added classifier metrics

models/classification/classifiers.py, models/pretraining/graph_infomax.py, models/pretraining/vgae.py
Added some documentation in DGI functions and set up the training pipeline for the ProtMotionNet and removed unused imports.
=> Added some documentation in DGI functions and set up the training pipeline for the ProtMotionNet and removed unused imports

models/classification/classifiers.py, models/pretraining/graph_infomax.py
=> Improved some documentation

models/layers.py, models/pretraining/decoders.py, models/pretraining/gae.py, models/pretraining/vgae.py
Refactored the GraphDecoder class and created a new type of decoder composed by point-wise feed-forward residual blocks.
=> Refactored the GraphDecoder class and created a new type of decoder composed by point-wise feed-forward residual blocks

models/pretraining/decoders.py
=> Removed TODOs

models/pretraining/vgae.py
=> Fixed a small bug

models/pretraining/graph_infomax.py, models/pretraining/vgae.py, training/pretraining/graph_infomax_train_script.py, training/pretraining/vgae_traning_script.py
Fixed a visualization bug in training functions.
=> Fixed a visualization bug

models/classification/dgcnn.py, models/classification/diffpool.py, models/classification/protmotionnet.py, preprocessing/preprocessing_script.py, training/classification/dgcnn_traning_script.py, training/classification/diffpool_traning_script.py
Started adding classification baselines.
=> Started adding classification baselines

log/logger.py, models/classification/classifiers.py, training/classification/dgcnn_traning_script.py, training/classification/diffpool_traning_script.py
=> Added more complex logging

models/classification/classifiers.py, training/classification/dgcnn_traning_script.py
Added option for label smoothing.
=> Added option for label smoothing

models/batch_utils.py, models/classification/gin.py, models/classification/multiset_baseline.py, models/classification/sage.py, training/classification/gin_traning_script.py, training/classification/multiset_baseline_traning_script.py, training/classification/sage_traning_script.py
Added more baselines and corresponding training scripts.
=> Added more baselines and corresponding training scripts

models/classification/classifiers.py, models/classification/pscdb_baseline.py, preprocessing/constants.py, preprocessing/dataset.py, preprocessing/edge_functions.py, preprocessing/preprocessing_script.py, training/classification/pscdb_baseline_traning_script.py
Added one more classifier baseline and a new type of dataset, which represents the before-after binding protein couple.
=> Added one more classifier baseline and a new type of dataset, which represents the before-after binding protein couple

models/classification/classifiers.py, models/classification/protmotionnet.py, preprocessing/dataset/dataset_creation.py, training/classification/dgcnn_traning_script.py, training/classification/diffpool_traning_script.py, training/classification/gin_traning_script.py, training/classification/multiset_baseline_traning_script.py, training/classification/pscdb_baseline_traning_script.py, training/classification/sage_traning_script.py
Added grid search to all classifiers.
=> Added grid search to all classifiers

models/classification/classifiers.py, training/classification/dgcnn_traning_script.py, training/classification/diffpool_traning_script.py, training/classification/multiset_baseline_traning_script.py, training/classification/pscdb_baseline_traning_script.py, training/classification/sage_traning_script.py
Small improvements and fixes in the classifiers scripts.
=> Small improvements and fixes in the classifiers scripts

models/classification/ugformer.py, models/pretraining/sampled_softmax.py, models/pretraining/ugformer_unsup.py, training/classification/ugtransformer_baseline_traning_script.py
=> Updated UGT-Unsup

models/pretraining/ugformer_unsup.py, preprocessing/constants.py, preprocessing/dataset/dataset_creation.py, preprocessing/preprocessing_script.py, training/pretraining/ugformer_unsup_train_script.py
Added ENZYMES and fold classification to preprocessing script.
=> Added ENZYMES and fold classification to preprocessing script

models/pretraining/ugformer_unsup.py, preprocessing/utils.py, training/pretraining/ugformer_unsup_train_script.py
Fixed bug in enzymes and fold classification.
=> Fixed bug in enzymes and fold classification

models/batch_utils.py, models/classification/classifiers.py, models/classification/protmotionnet.py, models/pretraining/encoders.py, training/classification/paired_protmotionet_baseline_traning_script.py
Fixed bugs in classifiers, protmotionet paired and multi head cross attention masks.
=> Fixed bugs in classifiers, protmotionet paired and multi head cross attention masks

models/classification/diffpool.py, models/pretraining/encoders.py, models/pretraining/gunet.py, training/classification/paired_protmotionet_traning_script.py
=> Added G-UNet model

evaluation/ensemble.py, models/classification/classifiers.py, models/classification/diffpool.py, models/classification/gunet_classifier.py, models/classification/protmotionnet.py, models/layers.py, models/pretraining/gunet.py, training/classification/paired_protmotionet_traning_script.py, training/training_tools.py
Added G-UNet, added ensemble utility class and fixed bunch of bugs.
=> Added G-UNet, added ensemble utility class and fixed bunch of bugs

models/ensemble/__init__.py, models/ensemble/ensemble.py
=> Small refactoring

models/classification/classifiers.py, models/classification/protmotionnet.py, models/ensemble/ensemble.py
=> Small documentation updates

models/classification/protmotionnet.py, models/ensemble/ensemble.py, training/classification/paired_protmotionet_traning_script.py
Small bugfixes and improvements.
=> Small bugfixes and improvements

evaluation/constants.py, evaluation/ensemble_script.py, models/classification/diffpool.py, models/classification/protmotionnet.py, models/classification/sage.py, models/ensemble/__init__.py, models/ensemble/ensemble.py, models/pretraining/graph_infomax.py, models/pretraining/gunet.py, models/pretraining/vgae.py, preprocessing/dataset/dataset_creation.py, training/classification/paired_protmotionet_traning_script.py, training/classification/sage_traning_script.py, training/pretraining/graph_infomax_train_script.py, training/pretraining/vgae_traning_script.py
Fixed various bugs, added ensemble script and normal mode features to the pretraining dataset.
=> Fixed various bugs, added ensemble script and normal mode features to the pretraining dataset

models/classification/diffpool.py, models/classification/protmotionnet.py, models/pretraining/graph_infomax.py, models/pretraining/normal_modes.py, models/pretraining/vgae.py, preprocessing/dataset/dataset_creation.py, training/classification/paired_protmotionet_traning_script.py, training/classification/pre_trained_paired_protmotionet_traning_script.py, training/pretraining/vgae_traning_script.py, training/training_tools.py
Fixed various bugs, added pretrained training script and normal mode features to the pretraining dataset.
=> Fixed various bugs, added pretrained training script and normal mode features to the pretraining dataset

models/pretraining/graph_infomax.py, models/pretraining/normal_modes.py, models/pretraining/vgae.py, preprocessing/dataset/dataset_creation.py, preprocessing/preprocessing_script.py, training/pretraining/graph_infomax_train_script.py, training/pretraining/normal_mode_training_script.py
=> Fixed normal modes

models/pretraining/graph_infomax.py, models/pretraining/normal_modes.py, training/classification/pre_trained_paired_protmotionet_traning_script.py, training/pretraining/graph_infomax_train_script.py, training/pretraining/normal_mode_training_script.py
Fixed normal modes training bugs.
=> Fixed normal modes training bugs
